-dontwarn io.netty.**
-dontwarn javax.naming.**
-dontwarn javax.security.**
-dontwarn jnr.unixsocket.**
-dontwarn org.bson.codecs.kotlin.**
-dontwarn org.bson.codecs.kotlinx.**
-dontwarn org.bson.codecs.record.**
-dontwarn org.ietf.jgss.**
-dontwarn org.xerial.snappy.**
-dontwarn software.amazon.awssdk.**
-keep class com.mongodb.** { *; }
-keep class org.bson.** { *; }
-dontwarn com.amazonaws.**
-dontwarn com.github.luben.zstd.**
-dontwarn com.mongodb.crypt.capi.**
-dontwarn java.lang.management.**
-dontwarn javax.annotation.**
-dontwarn javax.management.**
